version: '3.8'
services:
  mariadb:
    image: bitnami/mariadb:11.2
    container_name: mariadb
    volumes:
      - mariadb_data:/bitnami/mariadb
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MARIADB_USER=cxcxc_wp_db_user
      - MARIADB_PASSWORD=cxcxc+123456
      - MARIADB_ROOT_PASSWORD=cxcxc+123456
      - MARIADB_DATABASE=cxcxc_wp_db
  wordpress:
    image: bitnami/wordpress:6
    container_name: wordpress
    ports:
      - 80:8080
      - 443:8443
    volumes:
      - wordpress_data:/bitnami/wordpress
    depends_on:
      - mariadb
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - WORDPRESS_DATABASE_HOST=mariadb
      - WORDPRESS_DATABASE_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=cxcxc_wp_db_user
      - WORDPRESS_DATABASE_NAME=cxcxc_wp_db
      - WORDPRESS_DATABASE_PASSWORD=cxcxc+123456
      - WORDPRESS_USERNAME=cxcxc-wp-user
      - WORDPRESS_PASSWORD=cxcxc+123456
volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local
